import React, { useState } from 'react';
import { Slide, Source } from '../types';
import { ChevronRight, ChevronLeft, ExternalLink, Presentation, Cpu, Search } from './Icons';

interface PresentationDeckProps {
  slides: Slide[];
  sources: Source[];
  topic: string;
  onReset: () => void;
}

const PresentationDeck: React.FC<PresentationDeckProps> = ({ slides, sources, topic, onReset }) => {
  const [currentSlide, setCurrentSlide] = useState(0);

  const nextSlide = () => setCurrentSlide(prev => Math.min(prev + 1, slides.length - 1));
  const prevSlide = () => setCurrentSlide(prev => Math.max(prev - 1, 0));

  const activeSlide = slides[currentSlide];

  return (
    <div className="w-full max-w-5xl mx-auto animate-fade-in">
      
      {/* Header Actions */}
      <div className="flex justify-between items-center mb-6">
        <button 
          onClick={onReset}
          className="text-zinc-500 hover:text-white text-sm flex items-center transition-colors"
        >
          ← New Research
        </button>
        <div className="text-xs font-mono text-zinc-600 bg-black px-3 py-1 rounded-full border border-zinc-900">
          GENERATED BY CODEHOLICS_V1
        </div>
      </div>

      {/* Main Slide Area */}
      <div className="relative aspect-video bg-gradient-to-br from-zinc-950 to-zinc-900 rounded-xl border border-zinc-800 overflow-hidden shadow-2xl flex flex-col">
        
        {/* Slide Background Design Elements */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-violet-600/10 rounded-full blur-3xl -mr-32 -mt-32 pointer-events-none"></div>
        <div className="absolute bottom-0 left-0 w-96 h-96 bg-fuchsia-600/10 rounded-full blur-3xl -ml-32 -mb-32 pointer-events-none"></div>
        
        {/* Progress Bar */}
        <div className="h-1 w-full bg-zinc-900 flex">
          {slides.map((_, idx) => (
            <div 
              key={idx}
              className={`h-full flex-1 transition-all duration-300 ${
                idx <= currentSlide ? 'bg-violet-600' : 'bg-transparent'
              }`}
            />
          ))}
        </div>

        {/* Slide Content */}
        <div className="flex-1 p-12 flex flex-col justify-center relative z-10">
          <div className="flex items-center space-x-3 mb-6">
             <div className="p-2 bg-violet-500/10 rounded-lg border border-violet-500/20">
                <Cpu className="w-6 h-6 text-violet-400" />
             </div>
             <span className="text-violet-500 font-mono text-sm uppercase tracking-widest">Executive Brief</span>
          </div>

          <h1 className="text-4xl md:text-5xl font-bold text-white mb-8 leading-tight">
            {activeSlide.title}
          </h1>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="md:col-span-2 space-y-4">
              {activeSlide.points.map((point, idx) => (
                <div key={idx} className="flex items-start space-x-3">
                  <span className="mt-1.5 w-1.5 h-1.5 bg-fuchsia-400 rounded-full flex-shrink-0 shadow-[0_0_8px_rgba(232,121,249,0.8)]"></span>
                  <p className="text-lg text-zinc-300 leading-relaxed">{point}</p>
                </div>
              ))}
            </div>
            
            {/* Metric Card (if exists) or Summary */}
            <div className="md:col-span-1">
              {activeSlide.metric ? (
                <div className="bg-zinc-900/50 border border-zinc-800 p-6 rounded-xl backdrop-blur-sm mb-6">
                  <span className="text-zinc-500 text-xs uppercase tracking-wider block mb-2">Key Figure</span>
                  <span className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-fuchsia-400 to-violet-400">
                    {activeSlide.metric}
                  </span>
                </div>
              ) : null}
              
              <div className="bg-zinc-900/30 border-l-2 border-indigo-500 p-4 rounded-r-lg">
                <span className="text-indigo-400 text-xs font-bold uppercase tracking-wider block mb-2">Speaker Notes</span>
                <p className="text-sm text-zinc-400 italic">
                  "{activeSlide.summary}"
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-zinc-900 flex justify-between items-center bg-black/20 backdrop-blur-sm">
            <div className="text-zinc-600 text-sm font-mono">
                SLIDE {currentSlide + 1} / {slides.length}
            </div>
            <div className="flex space-x-4">
                <button 
                    onClick={prevSlide} 
                    disabled={currentSlide === 0}
                    className="p-2 rounded-full hover:bg-zinc-800 disabled:opacity-30 disabled:cursor-not-allowed transition-colors border border-zinc-800"
                >
                    <ChevronLeft className="w-5 h-5 text-white" />
                </button>
                <button 
                    onClick={nextSlide} 
                    disabled={currentSlide === slides.length - 1}
                    className="p-2 rounded-full hover:bg-zinc-800 disabled:opacity-30 disabled:cursor-not-allowed transition-colors border border-zinc-800 bg-zinc-900"
                >
                    <ChevronRight className="w-5 h-5 text-white" />
                </button>
            </div>
        </div>
      </div>

      {/* Sources Section */}
      <div className="mt-12 mb-20">
        <h3 className="text-lg font-semibold text-white mb-4 flex items-center">
            <Search className="w-4 h-4 mr-2 text-zinc-500" />
            Research Sources
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {sources.map((source, idx) => (
                <a 
                    key={idx} 
                    href={source.uri} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="group block p-4 bg-zinc-900/40 border border-zinc-800 hover:border-violet-500/50 hover:bg-zinc-900 rounded-lg transition-all"
                >
                    <div className="flex justify-between items-start">
                        <p className="text-sm text-zinc-400 font-medium line-clamp-2 group-hover:text-violet-300 transition-colors">
                            {source.title}
                        </p>
                        <ExternalLink className="w-3 h-3 text-zinc-700 group-hover:text-violet-500 flex-shrink-0 ml-3" />
                    </div>
                    <p className="text-xs text-zinc-600 mt-2 font-mono truncate">
                        {new URL(source.uri).hostname}
                    </p>
                </a>
            ))}
        </div>
      </div>

    </div>
  );
};

export default PresentationDeck;